/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jokeWizard;

import java.util.ArrayList;
import java.util.Random;

public class JokeWizard {

    private ArrayList<String> jokes;
    private Random random;
    private String lastUsedJoke;

    public JokeWizard() {
        jokes = new ArrayList<>();
        random = new Random();

        initializeJokeArrayList();
    }

    public String getJoke() {
        String joke = jokes.get(getRandomIndex());
        jokes.remove(joke);
        if(jokes.isEmpty()) {
            initializeJokeArrayList();
        }

        //this checks we don't immediately use the last joke
        //this could be the case if the array was re-initialized and the random joke happens
        //to be the last one used previously
        if(joke.equals(lastUsedJoke)) {
            return getJoke();
        } else {
            lastUsedJoke = joke;
            return joke;
        }

    }

    private int getRandomIndex() {
        int index;

        if(jokes.size() == 1) {
            index = 0;
        } else {
            index = random.nextInt(jokes.size());
        }

        return index;
    }

    private void initializeJokeArrayList() {
        jokes.add("How do you throw a space party? You planet!");
        jokes.add("Rest in peace boiling water. You will be mist!");
        jokes.add("Two artists had an art contest. It ended in a draw!");
        jokes.add("What do you call a pony with a cough? A little horse!");
        jokes.add("What's a foot long and slippery? A slipper!");
        jokes.add("I invented a new word today. Plagiarism.");
        jokes.add("What is sticky and brown? A stick!");
        jokes.add("What do you call a singing laptop? A Dell!");
        jokes.add("Why was six afraid of seven? Because seven ate nine.");
        jokes.add("Why did the orange stop? It ran out of juice!");
        jokes.add("I was wondering why the frisbee was getting bigger, then it hit me.");
        jokes.add("What do you call bears with no ears? B.");
        jokes.add("I have a fear of speed bumps. But I am slowly getting over it.");
        jokes.add("Talk is cheap? Have you ever talked to a lawyer?");
        jokes.add("What are shark's two most favorite words? Man overboard!");
        jokes.add("If we shouldn't eat at night, why do they put a light in the fridge?");
        jokes.add("What did the buffalo say when his son left for college? Bison!");
        jokes.add("What did one plate say to his friend? Tonight, dinner's on me!");
        jokes.add("I tried to sure the airport for misplacing my luggage. I lost my case.");
        jokes.add("How do trees get online? They just log on!");
    }

    public boolean someLibraryMethod() {
        return true;
    }

}
