/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jokeWizard;

import org.junit.Test;
import static org.junit.Assert.*;

public class JokeWizardTest {
    @Test public void testSomeLibraryMethod() {
        JokeWizard classUnderTest = new JokeWizard();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
